### PR TITLE
Update logsearch manifests to use logsearch-for-cloudfoundry-v1

### PR DESCRIPTION
**Pull request by mrdavidlaing**
Updates to use logsearch v19 (pre-release) and logsearch-for-cloudfoundry addon v1

### CODE REVIEW

**Comment by rkoster** [comment]
@mrdavidlaing long and I cleaned up the templates a little bit. 

Also you are correct about the subfolder. It does not work I mis read your issue. It currently is not supported to have a bosh relesae in a subfolder. @longnguyen11288 created https://github.com/cloudfoundry-incubator/bosh-workspace/issues/39 for it.

**Comment by mrdavidlaing** [comment]
Cool - thanks for the update

On Thursday, April 2, 2015, Ruben Koster notifications@github.com wrote:

> @mrdavidlaing https://github.com/mrdavidlaing long and I cleaned up the
> templates a little bit.
> 
> Also you are correct about the subfolder. It does not work I mis read your
> issue. It currently is not supported to have a bosh relesae in a subfolder.
> @longnguyen11288 https://github.com/longnguyen11288 created
> cloudfoundry-incubator/bosh-workspace#39
> https://github.com/cloudfoundry-incubator/bosh-workspace/issues/39 for
> it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cloudfoundry-community/logsearch-boshworkspace/pull/14#issuecomment-88941332
> .

## 

David Laing
logsearch.io - build your own open source cloud logging cluster
http://davidlaing.com

**Comment by rkoster** [comment]
If you are fine with the changes I will merge

**Comment by mrdavidlaing** [comment]
All looks good to me.  Thanks for the education and cleanup.  Merge away!

**Comment by rkoster** [comment]
Done :smile:

**Pull request merged**
